//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsuranceAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insuree
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAdresss { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string CarYear { get; set; }
        public string CarMake { get; set; }
        public Nullable<int> CarModel { get; set; }
        public Nullable<bool> DUI { get; set; }
        public Nullable<int> SpeedingTickets { get; set; }
        public Nullable<bool> CoverageType { get; set; }
        public Nullable<decimal> Quote { get; set; }
    }
}
